import numpy as np
import pandas as pd
df = pd.read_csv("employees_1000.csv")
print(df.head())
print(df.info())
print(df.describe())
print(df['salary'].mean())
print(df['salary'].median())
print(df['salary'].mode())
print(df.isnull().sum())
print(df['department'].value_counts())
print(df.groupby('department')['salary'].mean())
print(df.groupby('department')['salary'].median())
print(df.groupby('department')['salary'].max())
print(df.groupby('department')['salary'].min())
print(df.groupby('department')['salary'].std())
print(df.groupby('department')['salary'].var())
print(df.groupby('department')['salary'].count())
print(df.groupby('department')['salary'].sum())
print(df.sort_values(by='salary', ascending=False).head(10))
print(df.sort_values(by='salary', ascending=True).head(10))
print(df[df['salary'] > 100000])
print(df[df['salary'] < 50000])
print(df[df['department'] == 'sales'])
print(df[df['department'] == 'engineering'])
print(df[df['department'] == 'marketing'])
print(df[df['department'] == 'hr'])
print(df[df['department'] == 'finance'])
df['new_salary'] = df['salary'] * 1.1
print(df.head())
print(df[df['new_salary'] > 100000])
print(df[df['new_salary'] < 50000])
df['salary_range'] = pd.cut(df['salary'], bins=[0, 50000, 100000, 150000, 200000], labels=['0-50k', '50k-100k', '100k-150k', '150k-200k'])
print(df['salary_range'].value_counts())