import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
df=pd.read_csv('netflix_titles.csv')
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df.fillna(0))
print(df['type'].value_counts())
print(df[df['type']=='Movie'])
print(df[df['type']=='TV Show'])
print(df.columns)
print(df['release_year'].unique())
print(df.groupby('release_year')['type'].count())
plt.hist(df['release_year'].dropna(), bins=20)
plt.xlabel('Release Year')
plt.ylabel('Frequency')
plt.title('Distribution of Release Years')
plt.show()
plt.bar(df['type'], df['release_year'])
plt.xlabel('Type')
plt.ylabel('Release Year')
plt.title('Release Year by Type')
plt.show()
